### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by thanhhff** [KhacQuyDinh/DEV-C_Exercises#1]
Nhận xét: 
1. Phần SQL bạn có sử dụng đa dạng trên MS SQL Server và MYSQL.
2. Phần Python trong Task 5 bạn có thể dùng np.sort() để nhanh chóng hơn nhé !

**Comment by KhacQuyDinh** [comment]
Em đã sửa dùng np.sort rồi ạ, thanks anh.

**Comment by KhacQuyDinh** [comment]
Nếu đánh giá độ phức tạp thuật toán thì em thấy, np.sort sẽ là O(nlog(n)) còn cách em chỉ là O(n) cho bài này.
Khi em thử tính thời gian thì với n nhỏ cách cũ của em sẽ tốt hơn, và cách np.sort thì tốt hơn với n lớn.
Nhưng tận dụng hàm có sẵn trong python thường sẽ nhanh hơn với đa số các bài ạ :))

**Comment by thanhhff** [comment]
Yeah, mình có thể làm nhiều cách khác nhau. Nhưng dùng các function có sẵn thì luôn tiện lợi về mặt số dòng code và mức độ tối ưu cho các bài toán lớn.
