### ISSUE TITLE
Assignment - 02: Pandas & Seaborn

### ISSUE THREAD

**Issue by thanhhff** [KhacQuyDinh/DEV-C_Exercises#2]

**Comment by KhacQuyDinh** [comment]
what is the matter?

**Comment by hieutrluu** [comment]
Congratulations, you have done well on this assignment. Keep it up
Not many people made comments on the insight found in the bonus part so well done on that. 

Do you want us to comment on your assignment in English form now?

**Comment by KhacQuyDinh** [comment]
Thank you very much for your valuable comments.
Yah, you can give me comments in English from now on.

**Comment by KhacQuyDinh** [comment]
Dear HieuTrLuu,
Please tell me that how the first rank person in this assignment performs better than me so that I can improve my skills.
